tournament/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout

from . import views


urlpatterns = [
    url(r'^$', views.TournamentsView.as_view(), name='tournaments'),
    url(r'^logout\?next_page=(?P<next_page>.*)$', logout, name='logout'),
    url(r'^login$',
        views.LoginFormView.as_view(), name='login'),
    url(r'^delete/(?P<id>\d+)$',
        views.TournamentDeleteView.as_view(), name='tournament_delete'),
    url(r'^tournament-create-form$',
        views.TournamentCreateTemplateView.as_view(),
        name='tournament_create_form'),
    url(r'^create$',
        views.TournamentCreateView.as_view(), name='tournament_create'),
    url(r'^tournament/(?P<id>.+)$',
        views.TournamentView.as_view(), name='tournament'),
    url(r'^matches/update/$',
        views.MatchesUpdate.as_view(), name='matches_update'),
]

tournament_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('tournament.urls', namespace='tournament')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

tournament/models.py
# -*- coding: utf-8 -*
from __future__ import unicode_literals

from django.db import models


class Tournament(models.Model):
    ROUND_ROBIN = 'Круговой турнир'
    PLAYOFF = 'Олимпийская система (только плей-офф)'
    ROUND_PLAYOFF = 'Круговой + плей-офф'
    STYLE_CHOICES = (
        (1, ROUND_ROBIN),
        (2, PLAYOFF),
        (3, ROUND_PLAYOFF),
    )

    name = models.CharField(verbose_name='Название', max_length=100)
    style = models.IntegerField(
        choices=STYLE_CHOICES, verbose_name='Тип турнира')
    is_subgroups = models.BooleanField(verbose_name='Подгруппы', default=False)
    winner = models.ForeignKey('Participant', null=True, blank=True)
    is_count_ps_playoff_eq_len_ps = models.BooleanField(
        verbose_name='Количество участников для плейофф равно общему количеству участников', default=False)

    class Meta:
        verbose_name = 'Турнир'
        verbose_name_plural = 'Турниры'

    def __unicode__(self):
        return '{0}, Тип: {1}'.format(self.name, self.get_style_display())


class Participant(models.Model):
    name = models.CharField(verbose_name='Название', max_length=100)

    class Meta:
        verbose_name = 'Участник'
        verbose_name_plural = 'Участники'

    def __unicode__(self):
        return '{0}'.format(self.name)


class Match(models.Model):
    A = 'A'
    B = 'B'
    C = 'C'
    D = 'D'
    GROUP_CHOICES = (
        (1, A),
        (2, B),
        (3, C),
        (4, D),
    )

    tournament = models.ForeignKey('Tournament')
    participant1 = models.ForeignKey(
        'Participant', verbose_name='Первый игрок',
        related_name='participant1', null=True
    )
    participant2 = models.ForeignKey(
        'Participant', verbose_name='Второй игрок',
        related_name='participant2', null=True
    )
    date = models.DateField(verbose_name='Дата', null=True, blank=True)
    result = models.CharField(
        verbose_name='Результат', max_length=10, null=True)
    winner = models.ForeignKey('Participant', null=True)
    prev_match1 = models.ForeignKey(
        'Match', related_name='match1', null=True, blank=True)
    prev_match2 = models.ForeignKey(
        'Match', related_name='match2', null=True, blank=True)
    level = models.SmallIntegerField(null=True, blank=True)
    group = models.SmallIntegerField(
        choices=GROUP_CHOICES, null=True, blank=True)

    class Meta:
        verbose_name = 'Матч'
        verbose_name_plural = 'Матчи'

    def __unicode__(self):
        return 'Турнир: {0}, дата: {1}'.format(self.tournament.name, self.date)


class Set(models.Model):
    match = models.ForeignKey('Match')
    set_number = models.SmallIntegerField(verbose_name='Номер сета')
    points1 = models.SmallIntegerField(verbose_name='Очки первого игрока')
    points2 = models.SmallIntegerField(verbose_name='Очки второго игрока')

tournament/forms.py
# -*- coding: utf-8 -*
from django import forms


class LoginForm(forms.Form):
    name = forms.CharField(label=u'Имя пользователя', required=True)
    password = forms.CharField(label=u'Пароль', required=True)

tournament/views.py
# -*- coding: utf-8 -*
from django.views.generic import ListView, TemplateView, FormView
from django.views.generic.edit import BaseDeleteView
from django.views import View

from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.shortcuts import render, get_object_or_404

from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth import authenticate, login, logout

from django.db.models import Min, Max, Case, When, Value, CharField

from django.urls import reverse_lazy

from .models import Tournament, Participant, Match, Set
from .utils import get_group_counts, get_list_of_list
from .forms import LoginForm

import random
import math
import datetime
import json


class JSONResponseMixin(object):

    def render_to_json_response(self, context, **response_kwargs):
        return JsonResponse(
            self.get_data(context), safe=False,
            **response_kwargs
        )

    def get_data(self, context):
        return context


class TournamentsView(ListView):
    template_name = u'tournament/tournaments.html'
    context_object_name = 'tournaments'
    queryset = Tournament.objects.annotate(
        early_date=Min('match__date'), last_date=Case(
            When(winner__isnull=False, then=Max('match__date')),
            default=Value(None),
            outuput_field=CharField()
        )
    ).order_by('early_date', '-id')


class LogoutView(View):

    def get(self, request):
        logout(request)
        return HttpResponseRedirect(request.GET.get('next'))


class TournamentDeleteView(
    UserPassesTestMixin, JSONResponseMixin, BaseDeleteView
):
    login_url = reverse_lazy('tournament:login')
    model = Tournament

    def test_func(self):
        return self.request.user.is_superuser

    def get_object(self):
        try:
            obj = self.model.objects.get(id=self.kwargs['id'])
        except self.model.DoesNotExist:
            obj = None
        return obj

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object:
            self.object.delete()
        else:
            return HttpResponse(status=404)
        return HttpResponse(status=200)


class TournamentCreateTemplateView(UserPassesTestMixin, ListView):
    login_url = reverse_lazy('tournament:login')
    template_name = 'tournament/tournament-create-form.html'
    context_object_name = 'participants'
    queryset = Participant.objects.all().order_by('name')

    def test_func(self):
        return self.request.user.is_superuser


def create_round_robin_matches(participants, tournament, i=None):
    from competitions.scheduler import roundrobin
    scheduler = roundrobin.SingleRoundRobinScheduler(participants)
    for tour in scheduler.generate_schedule():
        for pair in tour:
            if None in pair:
                continue
            match = Match(tournament=tournament, participant1=pair[0],
                          participant2=pair[1])
            if i:
                match.group = i
            match.save()


def create_play_off_matches(participants, tournament):
    level = 0
    len_participants = len(participants)
    while level < math.log(len_participants, 2):
        matches = []
        for i in range(0, len(participants), 2):
            args = {
                'tournament': tournament,
                'level': level,
            }
            if level == 0:
                args.update({
                    'participant1': participants[i],
                    'participant2': participants[i+1],
                })
            else:
                args.update({
                    'prev_match1': participants[i],
                    'prev_match2': participants[i+1],
                })
            match = Match(**args)
            match.save()
            matches.append(match)
        level += 1
        if level > 0:
            participants = matches


def create_round_playoff_grouped(participants, tournament):
    participants_len = len(participants)
    group_counts = get_group_counts(participants_len)
    step_add = 0
    if participants_len % group_counts:
        step_add = 1
    step = participants_len / group_counts + step_add
    participants_grouped = get_list_of_list(participants, step)
    if len(participants_grouped[-1]) == 1:
        el = participants_grouped.pop()
        participants_grouped[-1].extend(el)
    for i, participants in enumerate(participants_grouped, start=1):
        create_round_robin_matches(participants, tournament, i)


def get_group_ids(ms):
    return list(set([m.group for m in ms]))


def get_grouped_tournament_table(ps, ms, group):
    ms = [m for m in ms if m.group == group]
    ps = get_participants(ms)
    return get_tournament_table(ps, ms)


def get_grouped_tables(ps, ms):
    tables = {}
    group_ids = get_group_ids(ms)
    groups = dict(Match.GROUP_CHOICES)
    for group_id in group_ids:
        group_name = groups[group_id]
        tables[group_name] = get_grouped_tournament_table(ps, ms)
    return tables


def get_count_of_ps_for_playoff(count):
    base = 2
    new_count = base ** (count.bit_length() - 1)
    if count != new_count or new_count == base:
        return new_count
    else:
        return get_count_of_ps_for_playoff(count - 1)


def get_group_count(matches):
    return len(set([match.group for match in matches if match.group]))


def get_min_participants_count_in_groups(matches):
    counts = {}
    for match in matches:
        if match.group:
            if match.group not in counts:
                counts[match.group] = {'count': 0, 'ps': []}
            counts[match.group]['ps'].append(match.participant1)
            counts[match.group]['ps'].append(match.participant2)
    for group, count_ps in counts.iteritems():
        count_ps['count'] = len(set(count_ps['ps']))
    return min([v['count'] for v in counts.values()])


def is_base_of_2_pow(num):
    return ((num & (num - 1)) == 0) and num > 0


def get_participants_for_playoff(tournament):
    ms = Match.objects.filter(tournament=tournament)
    ps = get_participants(ms)
    if tournament.is_subgroups:
        min_ps_in_group = get_min_participants_count_in_groups(ms)
        ps_len = min_ps_in_group * get_group_count(ms)
    else:
        ps_len = len(ps)
    if tournament.is_count_ps_playoff_eq_len_ps and is_base_of_2_pow(ps_len):
        count_of_ps_for_playoff = ps_len
    else:
        count_of_ps_for_playoff = get_count_of_ps_for_playoff(ps_len)

    table = get_tournament_table(ps, ms)[:count_of_ps_for_playoff]
    ps = [p[1]['participant'] for p in table]
    ps_new = []
    for i in range(len(ps)/2):
        ps_new.append(ps[i])
        ps_new.append(ps[len(ps)-i-1])
    return ps_new


def create_matches(tournament):
    style = tournament['style_name']
    participants = tournament['participants_obj']
    is_subgroups = tournament['is_subgroups']
    tournament = tournament['tournament_obj']
    random.shuffle(participants)
    if style == Tournament.ROUND_ROBIN:
        create_round_robin_matches(participants, tournament)
    elif style == Tournament.PLAYOFF:
        create_play_off_matches(participants, tournament)
    elif style == Tournament.ROUND_PLAYOFF:
        if is_subgroups:
            create_round_playoff_grouped(participants, tournament)
        else:
            create_round_robin_matches(participants, tournament)


class TournamentCreateView(UserPassesTestMixin, View):
    login_url = reverse_lazy('tournament:login')

    def test_func(self):
        return self.request.user.is_superuser

    def post(self, request, *args, **kwargs):
        tournament_data = json.loads(request.body)
        tournament = Tournament(
            name=tournament_data['name'], style=tournament_data['style'],
            is_subgroups=tournament_data['is_subgroups']
        )
        tournament.save()

        participants = []
        for participant in tournament_data['participants']:
            participant, _ = Participant.objects.get_or_create(
                name=participant)
            participants.append(participant)

        tournament_data['tournament_obj'] = tournament
        tournament_data['participants_obj'] = participants
        create_matches(tournament_data)

        return HttpResponse(status=200)


def get_splitted_result(result):
    dash = result.index('-')
    return result[:dash], result[dash+1:]


def is_draw(match):
    results = get_splitted_result(match.result)
    return match.result and results[0] == results[1]


def get_tournament_table(participants_qs, matches_qs):
    table = {}
    for p in participants_qs:
        if p is None:
            continue
        count = win_count = points = lose = goals_positive = goals_negative = 0
        for m in matches_qs:
            if m.result:
                if m.participant1 == p or m.participant2 == p:
                    count += 1
                    results = get_splitted_result(m.result)
                    goal_p1 = int(results[0])
                    goal_p2 = int(results[1])
                    if m.participant1 == p:
                        goals_positive += goal_p1
                        goals_negative += goal_p2
                    else:
                        goals_positive += goal_p2
                        goals_negative += goal_p1
                if m.winner and m.winner != p \
                        and (m.participant1 == p or m.participant2 == p):
                    lose += 1
            if m.winner == p:
                win_count += 1
                points += 3
            elif (m.participant1 == p or m.participant2 == p) and m.result \
                    and is_draw(m):
                points += 1
        tbl = {}
        tbl['count'] = count
        tbl['win_count'] = win_count
        tbl['points'] = points
        tbl['lose'] = lose
        sub_win_lose = goals_positive - goals_negative
        if sub_win_lose > 0:
            sub_win_lose = '+' + str(sub_win_lose)

tournament/templates/tournament/inc_schedule.html
    {% if matches %}
        <div class="tournament schedule" data-is-playoff="{{ is_playoff }}">
            <table>
                <thead>
                    <tr>
                        <td>Дата</td>
                        <td>Участники</td>
                        <td>Счёт</td>
                        <td>Победитель</td>
                        {% if is_playoff %}
                            <td>Стадия</td>
                        {% endif %}
                        {% if is_group %}
                            <td>Группа</td>
                        {% endif %}
                        <td class="match-additional-result">Расширенная информация по счёту</td>
                    </tr>
                </thead>
                <tbody>
                    {% for match in matches %}
                        {% if is_round %}
                            <tr
                                {% if forloop.counter == 1 %}
                                    class="tour-line-top"
                                {% else %}
                                    {% if forloop.counter|divisibleby:tour_step %}
                                        class="tour-line-bottom"
                                    {% endif %}
                                {% endif %}
                            data-match-id="{{ match.id }}">
                        {% else %}
                            <tr data-match-id="{{ match.id }}">
                        {% endif %}
                                <td class="match-date">{{ match.date|date:'d.m.Y' }}</td>
                                <td class="match-participants">{{ match.participant1 }} — {{ match.participant2 }}</td>
                                <td class="match-result">{{ match.result|default_if_none:'' }}</td>
                                <td class="match-winner">{{ match.winner_wrap }}</td>
                                {% if is_playoff %}
                                    <td class="match-level">{{ match.level_wrap }}</td>
                                {% endif %}
                                {% if is_group %}
                                    <td class="match-group">{{ match.get_group_display }}</td>
                                {% endif %}
                                <td class="match-additional-result">{{ match.additional_result }}</td>
                            </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}

tournament/templates/tournament/inc_tournament_points.html
            <div class="tournament">
                <table>
                    <thead>
                        <tr>
                            <td>Место</td>
                            <td>Участник</td>
                            <td>Очки</td>
                            <td>Количество игр</td>
                            <td>Победы</td>
                            <td>Поражения</td>
                            <td>Разница выигранных/проигранных партий</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for ps_name, ps_data in tournament_table %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ ps_name }}</td>
                                <td>{{ ps_data.points }}</td>
                                <td>{{ ps_data.count }}</td>
                                <td>{{ ps_data.win_count }}</td>
                                <td>{{ ps_data.lose }}</td>
                                <td>{{ ps_data.sub_win_lose }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

tournament/templates/tournament/login.html
{% extends 'index-base.html' %}
{% load staticfiles %}

{% block title %}
    Авторизация
{% endblock %}

{% block css %}
    {{ block.super }}
    <link href="{% static 'tournament/css/signin.css' %}" rel="stylesheet">
{% endblock %}

{% block body %}
    <form method="POST" class="form-signin">
        {% csrf_token %}
        <h2 class="form-signin-heading">Авторизация</h2>
        <input type="text" required placeholder="Имя пользователя" class="form-control" name="{{ form.name.name }}" value="{{ form.name.value|default_if_none:'' }}">
        <input type="password" required placeholder="Пароль" class="form-control" name="{{ form.password.name }}" value="{{ form.password.value|default_if_none:'' }}">
        <button type="submit" class="btn btn-lg btn-primary btn-block">OK</button>
        {% if state %}
            {{ state }}
        {% endif %}
    </form>
{% endblock %}

tournament/templates/tournament/tournament-create-form.html
{% extends 'index-base.html' %}
{% load staticfiles %}

{% block title %}
    Создание турнира
{% endblock %}

{% block js %}
    {{ block.super }}
    <script src="{% static 'js/lib/jquery/js.cookie.js' %}"></script>
    <script src="{% static 'tournament/js/manage_tournaments.js' %}"></script>
{% endblock %}

{% block body %}
    <div class="col-md-8">
        <form>
            <h1>Создание турнира</h1>
            <div class="form-group">
                <input type="text" class="form-control" id="input-tournament" placeholder="Название турнира" required>
            </div>
            <div class="form-group">
                <label for="tournament-style">Выберите формат турнира</label>
                <div class="radio">
                  <label>
                    <input type="radio" name="tournament-styles" id="options-radios1" value="1" data-name="Круговой турнир" checked>
                    Круговой турнир
                  </label>
                </div>
                <div class="radio">
                  <label>
                    <input type="radio" name="tournament-styles" id="options-radios2" value="2" data-name="Олимпийская система (только плей-офф)">
                    Олимпийская система (только плей-офф)
                  </label>
                </div>
                <div class="radio">
                  <label>
                    <input type="radio" name="tournament-styles" id="options-radios3" value="3" data-name="Круговой + плей-офф">
                    Круговой + плей-офф
                  </label>
                </div>
                <div class="checkbox col-md-offset-1" style="display:none">
                    <label>
                        <input type="checkbox" id="is-subgroups" disabled>Разделить на подгруппы
                    </label>
                </div>
            </div>
            <div class="form-group">
                {% if participants %}
                    <label for="tournament-participants">Выберите участников или команды</label>
                    <span id="participants-count">Выбрано: <span id="participants-count__value">0</span></span>
                    <select id="participants-select" class="form-control" size="5" multiple>
                        {% for participant in participants %}
                            <option value="{{ participant.id }}">{{ participant.name }}</option>
                        {% endfor %}
                    </select>
                {% endif %}
                <label for="tournament-participants">Для создания новых введите через запятую имена участников или названия команд</label>
                <textarea class="form-control" id="text-tournament-participants" rows="3" required></textarea>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary save-data">ГОТОВО</button>
                <img class="load-animate" src="{% static 'img/load.gif' %}" hidden>
                <button type="reset" class="btn btn-default">Отмена</button>
            </div>
        </form>
    </div>
{% endblock %}

tournament/templates/tournament/tournament.html
{% extends 'index-base.html' %}
{% load staticfiles %}

{% block title %}
    {{ tournament.name }}
{% endblock %}

{% block css %}
    {{ block.super }}
    <link href="{% static 'js/lib/jquery-ui/jquery-ui.min.css' %}" rel="stylesheet">
{% endblock %}

{% block js %}
    {{ block.super }}
    <script src="{% static 'js/lib/jquery/js.cookie.js' %}"></script>
    <script src="{% static 'js/lib/jquery-ui/jquery-ui.min.js' %}"></script>
    <script src="{% static 'tournament/js/manage_tournaments.js' %}"></script>
{% endblock %}

{% block body %}
    <div class="col-md-8">
        <div class="tournament-title tournament-data" data-tournament-name="{{ tournament.get_style_display }}">
            <strong>Турнир: {{ tournament.name }}<br>Тип: {{ tournament.get_style_display }}</strong>
        </div>
        {% if tournament.get_style_display != tournament.PLAYOFF %}
            <div class="tournament-title">
                <strong>Турнирная таблица</strong>
            </div>
            {% include 'tournament/inc_tournament_points.html' %}
        {% endif %}
        <div class="tournament-title">
            <strong>Расписание матчей</strong>
        </div>
        {% if tournament.get_style_display == tournament.ROUND_ROBIN %}
            {% include 'tournament/inc_schedule.html' with is_playoff=False is_round=True %}
        {% elif tournament.get_style_display == tournament.PLAYOFF %}
        {% include 'tournament/inc_schedule.html' with is_playoff=True matches=matches_playoff %}
        {% elif tournament.get_style_display == tournament.ROUND_PLAYOFF %}
            {% include 'tournament/inc_schedule.html' with is_playoff=False is_group=matches.0.group is_round=True %}
            {% if matches_playoff %}
                <div class="tournament-title">
                    <strong>Плей-офф</strong>
                </div>
            {% endif %}
            {% include 'tournament/inc_schedule.html' with is_playoff=True matches=matches_playoff %}
        {% endif %}
        {% if matches or matches_playoff %}
            {% if request.user.is_superuser %}
                <button id="save-matches" class="btn btn-primary save-data">Сохранить</button>
                <img class="load-animate" src="{% static 'img/load.gif' %}" hidden>
            {% endif %}
        {% endif %}
        <div class="winner">
            {% if winner %}
                Поздравляем <b>{{ winner }}</b> с победой!
            {% endif %}
        </div>
    </div>
{% endblock %}

tournament/templates/tournament/tournaments.html
{% extends 'index-base.html' %}
{% load staticfiles %}

{% block title %}
    Список турниров
{% endblock %}

{% block js %}
    {{ block.super }}
    <script src="{% static 'js/lib/jquery/js.cookie.js' %}"></script>
    <script src="{% static 'tournament/js/manage_tournaments.js' %}"></script>
{% endblock %}

{% block body %}
    <div class="col-md-8">
        <div class="tournaments-title">
            <h1>Турниры</h1>
            {% if request.user.is_superuser %}
                <a class="btn btn-primary" href="{% url 'tournament:tournament_create_form' %}" role="button">+Создать турнир</a>
            {% endif %}
        </div>
        <div class="tournaments">
            <div class="tournaments-list">
                {% if tournaments %}
                    <table>
                        <thead>
                            <tr>
                                <td>Название</td>
                                <td>Начало</td>
                                <td>Завершён</td>
                                <td>Победитель</td>
                                {% if request.user.is_superuser %}
                                    <td>
                                        Удалить
                                    </td>
                                {% endif %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for tournament in tournaments %}
                                <tr data-id="{{ tournament.id }}">
                                    <td class="tournament-name">
                                        <a href="{% url 'tournament:tournament' id=tournament.id %}">
                                            {{ tournament.name }}
                                        </a>
                                    </td>
                                    <td>
                                        {{ tournament.early_date|date:'d.m.y' }}
                                    </td>
                                    <td>
                                        {{ tournament.last_date|date:'d.m.y' }}
                                    </td>
                                    <td>
                                        {{ tournament.winner|default_if_none:'' }}
                                    </td>
                                    {% if request.user.is_superuser %}
                                        <td>
                                            <img src="{% static 'img/delete.png' %}">
                                        </td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    Турниры пока не созданы.
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}