tournament/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout

from . import views


urlpatterns = [
    url(r'^$', views.TournamentsView.as_view(), name='tournaments'),
    url(r'^logout\?next_page=(?P<next_page>.*)$', logout, name='logout'),
    url(r'^login$',
        views.LoginFormView.as_view(), name='login'),
    url(r'^delete/(?P<id>\d+)$',
        views.TournamentDeleteView.as_view(), name='tournament_delete'),
    url(r'^tournament-create-form$',
        views.TournamentCreateTemplateView.as_view(),
        name='tournament_create_form'),
    url(r'^create$',
        views.TournamentCreateView.as_view(), name='tournament_create'),
    url(r'^tournament/(?P<id>.+)$',
        views.TournamentView.as_view(), name='tournament'),
    url(r'^matches/update/$',
        views.MatchesUpdate.as_view(), name='matches_update'),
]

tournament_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('tournament.urls', namespace='tournament')),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/inc_username_indicate.html
        <div class="col-md-4">
            <div class="username {% if request.user.is_superuser %} superuser {% endif %}">
                {% if request.user.is_superuser %}
                    Привет, {{ request.user.username }}! <a href="{% url 'tournament:logout' next_page=request.path %}">выйти</a>
                {% else %}
                    Вы не авторизованы. <a href="{% url 'tournament:login' %}">Войти?</a>
                {% endif %}
            </div>
        </div>

templates/index-base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% block css %}
            <link href="{% static 'css/lib/bootstrap/bootstrap.min.css' %}" rel="stylesheet">
            <link href="{% static 'css/style.css' %}" rel="stylesheet">
        {% endblock %}
    </head>
    <body>
        <div class="container">
            <div class="row top-buffer">
                <div class="col-md-8">
                    <a href="{% url 'tournament:tournaments' %}">Главная</a>
                </div>
                {% include 'inc_username_indicate.html' %}
            </div>
            <div class="row bottom-buffer">
                {% block body %}
                {% endblock %}
            </div>
        </div>
        {% block js %}
            <script src="{% static 'js/lib/jquery/jquery.min.js' %}"></script>
            <script src="{% static 'js/lib/bootstrap/bootstrap.min.js' %}"></script>
        {% endblock %}
    </body>
</html>